# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a59d2edca1614499b3e0eed3f1c6736b717480b76b9702a3adc0453a05430bee02fb47555c8f395a598dcdf05736d18acb7d7ab80df06fb5775776950fec04d

test:
  secret_key_base: bb69605caa7dcc5cbdb777bf73ca1908d897931055690db2638427d0ef2699279958b30b64f03d49a55c84c14fc5d1a05d4db50fbedd07194f18c823deab5e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
